# Build settings
plugins:
  - octopress-image-tag
  - octopress-solarized
  - jekyll-paginate
  - jekyll-gist

repository: samwize/samwize.com

# Site settings
title: "@samwize"
description: > # this means to ignore newlines until "email:"
   ¯\_(ツ)_/¯

email: junda@just2us.com
# blog logo
logo: ""
# blog cover
cover: "/assets/profile/cover-2015.jpg"

permalink: /:year/:month/:day/:title/

name: 'Junda Ong'
author: 'Junda Ong'
author_image: "/assets/profile/profile-pic-2015.jpg"

paginate:	30

url: "https://samwize.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@samwize'

#fill in disqus shortname to use disqus
disqus: just2us

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/samwize
    desc: 	Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/ongjunda
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/samwize
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	https://plus.google.com/u/0/+JundaOng/posts
    desc:	Add me on google+
    share_url: https://plus.google.com/share
    share_title: ?t=
    share_link: "&amp;url="
